import React,{useState} from 'react'; import {createRoot} from 'react-dom/client'; import {Provider,useDispatch,useSelector} from 'react-redux'; import {RootState,store,setDraft,setAssessment,setLoading,setError,reset} from './store'; import './styles.css';
const API='http://localhost:8000/api';
function App(){const d=useDispatch();const {draft,assessment,loading,error}=useSelector((s:RootState)=>s.intake);const [records,setRecords]=useState<any[]>([]);const [text,setText]=useState('Dear Quality Team,\n\nWe received reports that Paracetamol 500mg tablets from Batch PCT-24091 have cracked tablets and broken blisters. Please investigate urgently.\n\nRegards, MedSupply Distribution, India');
const analyse=async()=>{d(setLoading(true));d(setError(''));try{const r=await fetch(`${API}/complaints/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok)throw Error('Analysis failed');const x=await r.json();d(setDraft(x.complaint));d(setAssessment(x.assessment))}catch(e:any){d(setError(e.message))}finally{d(setLoading(false))}};
const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const b=new FormData();b.append('file',f);const r=await fetch(`${API}/documents/extract`,{method:'POST',body:b});const x=await r.json();setText(x.text)};
const save=async()=>{if(!assessment)return;const r=await fetch(`${API}/complaints`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,status:'Open',risk_level:assessment.risk_level,risk_score:assessment.risk_score,ai_assessment:assessment})});if(r.ok){const x=await r.json();setRecords([x,...records]);d(reset());setText('');}};
const field=(key:keyof typeof draft,label:string)=><label>{label}<input value={draft[key]} onChange={e=>d(setDraft({[key]:e.target.value}))}/></label>;
return <main><aside><div className="brand">aivoa<span>.ai</span></div><p>QUALITY MANAGEMENT</p><button className="nav active">✦ Complaint Copilot</button><button className="nav">▣ Complaint Register</button><button className="nav">◌ CAPA</button><div className="sidefoot">Demo workspace<br/><b>Quality Assurance</b></div></aside><section><header><div><span className="eyebrow">CUSTOMER COMPLAINTS</span><h1>Log a customer complaint</h1><p>AI-assisted intake for a reviewable QMS workflow.</p></div><div className="badge">● GxP review required</div></header><div className="grid"><div className="card source"><h2>1. Intake source</h2><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste an email or complaint narrative…"/><div className="actions"><label className="upload">Upload PDF / text<input type="file" accept=".pdf,.txt,.md" onChange={upload}/></label><button className="primary" onClick={analyse} disabled={loading}>{loading?'Analysing…':'✦ Analyse with AI'}</button></div>{error&&<p className="error">{error}</p>}</div><div className="card ai"><h2>AI Copilot risk assessment</h2>{assessment?<><div className={`risk ${assessment.risk_level.toLowerCase()}`}>{assessment.risk_level}<strong>{assessment.risk_score}/100</strong></div><p>{assessment.rationale}</p><h3>Completeness check</h3>{assessment.missing_information.length?<ul>{assessment.missing_information.map((x:string)=><li key={x}>Missing: {x}</li>)}</ul>:<p className="ok">✓ Core intake fields identified</p>}<h3>Recommended next step</h3><p>{assessment.capa_recommendation}</p></>:<div className="empty">Run an analysis to see transparent risk, completeness, duplicate, and CAPA guidance.</div>}</div></div><div className="card form"><h2>2. Complaint record <span>Review AI-extracted fields</span></h2><div className="fields">{field('product_name','Product name')}{field('batch_number','Batch / Lot')}{field('complaint_type','Complaint type')}{field('country','Country / Market')}{field('customer_name','Customer / Reporter')}{field('received_date','Date received')}</div><label>Complaint description<textarea value={draft.description} onChange={e=>d(setDraft({description:e.target.value}))}/></label><div className="save"><small>Saving creates an immutable intake record. Quality must approve all AI recommendations.</small><button className="primary" disabled={!assessment} onClick={save}>Save complaint record</button></div></div>{records.length>0&&<div className="card register"><h2>Created this session</h2>{records.map(r=><div key={r.id}><b>{r.complaint_number}</b> · {r.product_name} <span className={`pill ${r.risk_level.toLowerCase()}`}>{r.risk_level}</span></div>)}</div>}</section></main>}
createRoot(document.getElementById('root')!).render(<Provider store={store}><App/></Provider>);
